// This file imports the auto-generated registry
// The actual registry is generated by running: npm run generate:registry

import {
  availableBlocks,
  registryMetadata,
  registryPreviewComponents,
  registrySourceCode,
} from "./registry.generated";

export {
  registryPreviewComponents,
  registrySourceCode,
  registryMetadata,
  availableBlocks,
  type BlockKey,
} from "./registry.generated";

// Helper functions for working with the registry
export const getBlockComponent = (key: string) => {
  return registryPreviewComponents[
    key as keyof typeof registryPreviewComponents
  ];
};

export const getBlockSourceCode = (key: string) => {
  return registrySourceCode[key as keyof typeof registrySourceCode];
};

export const getBlockMetadata = (key: string) => {
  return registryMetadata[key as keyof typeof registryMetadata];
};

export const getAllBlocks = () => {
  return availableBlocks.map((key) => ({
    key,
    ...getBlockMetadata(key),
    component: getBlockComponent(key),
    sourceCode: getBlockSourceCode(key),
  }));
};
