import NextThemeProvider from "@/components/next-theme-provider";
import { GeistSans } from "geist/font/sans";
import { Inter } from "next/font/google";

import { cn } from "@/lib/utils/tailwind";
import "./_styles/globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Trong Duong",
  description: "Generated by Trong Duong",
  keywords: "Trong Duong | Personal Portfolio",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(GeistSans.variable, "font-geist-sans")}>
        <NextThemeProvider>{children}</NextThemeProvider>
      </body>
    </html>
  );
}
